const fs = require("fs");
const path = require("path");

const dataPath = path.join(__dirname, "..", "data", "sample", "bio_experiments.json");
const outputPath = path.join(__dirname, "..", "reports", "BioDockLab_Report_Node.md");

const experiments = JSON.parse(fs.readFileSync(dataPath, "utf-8"));

const lines = [];

lines.push("# BioDockLab Research Report");
lines.push("");
lines.push(`Generated by Node.js at: ${new Date().toISOString()}`);
lines.push("");
lines.push("## Experiment Summary");
lines.push("");

experiments.forEach((exp) => {
  lines.push(`### ${exp.id} - ${exp.domain}`);
  lines.push("");
  lines.push(`- Sample: ${exp.sample}`);
  lines.push(`- Condition: ${exp.condition}`);
  lines.push(`- Success Rate: ${exp.success_rate}%`);
  lines.push(`- Risk Level: ${exp.risk_level}`);
  lines.push(`- Note: ${exp.note}`);
  lines.push("");
});

fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");

console.log(`Report generated: ${outputPath}`);